name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 8.0.275
      - name: echo java home
        run: echo $JAVA_HOME
      - name: set java8 home
        run: |
          export JAVA8_HOME=$JAVA_HOME && echo $JAVA8_HOME
          echo "::set-env name=JAVA8_HOME::$JAVA_HOME"
      - name: echo java8 home 
        run:  echo $JAVA8_HOME

      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: echo java home
        run: echo $JAVA_HOME && ls /opt/hostedtoolcache/jdk/8.0.275/x64
      # - name: Build with Maven
      #   run: mvn package -DskipTests && mvn test
